#include <stdio.h>
#include <stdlib.h>
/*********************************/
#include "metalang99/include/metalang99.h"
/*********************************/
#include "interface99/interface99.h"
/*********************************/
#include "log/log.c"
/*********************************/
#include "include/rrd.h"
/*********************************/
#define PASSWORD                   "5c66f870-c0a3-4ba3-b7e6-839ce0d4ea5c"
#define B64_ENCODED_PRIVATE_KEY    "x"
//LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUJsd0FBQUFkemMyZ3RjbgpOaEFBQUFBd0VBQVFBQUFZRUF0OGtISjU5SkFqNkZWYk8zakV6ZXNSeS93TDNjeDErZ21TRTFkcWV2ZUY2NkJ6OE5oOWZKCkgwRkpubzlSRVhNRFJWV2FtREFFMHVWcFNlUFl0c2lEdXZZNThmNGdVYmtrOC9ac3I0cTFXMTBRNXdNbzFlOS9oOVpIaXUKUHp3V0ZBcE52YUxpRmVtelRRTldKdjRURlVSRmh6blJHYlNMZTZ3VXUrV2RYaitnTUFkYzBJMEg1UHgwcloyTklSQnBLWgptU1duY3NEQVptZjhvTUVTM0VqNFJTbytRL29HZGZxYy9OS1ZGZWxqdjJOakxROUlPNjBYc2M2bHJCREhQUXV1RkVRMmFCCjkyamx2TXczQTlkWkxNWGNkRndMVUt0MWpFcFkzNHFMVE42YW9SeWUxSURsWFdPZXV1SzVaT1B1S2JwRVpDY21ENFM0ZkgKMlA4NmxNemZmUGpBMnZWQXpWanlDT1BYd0F0VU5HblQ4WVBVQU9DblRySkhjNHI1ZkU4cUEvTWhrWHVkbWlpbVc1Tkxrawozc2NLUVBGS1ZHY2xpV1VLRTVqeWwvbUI3WGdBTkNlY3RyNjdaQ1NxeUlBeU5IL3RjVVFwcE0zUmEzM1FUM3ArUVNScTNmCnMwTjNOUDh6RzZPbzEvcWozNUQ5ZU42SkJsbk5zL3VmQ2JmajdPTlZBQUFGbUhVMCt6bDFOUHM1QUFBQUIzTnphQzF5YzIKRUFBQUdCQUxmSkJ5ZWZTUUkraFZXenQ0eE0zckVjdjhDOTNNZGZvSmtoTlhhbnIzaGV1Z2MvRFlmWHlSOUJTWjZQVVJGegpBMFZWbXBnd0JOTGxhVW5qMkxiSWc3cjJPZkgrSUZHNUpQUDJiSytLdFZ0ZEVPY0RLTlh2ZjRmV1I0cmo4OEZoUUtUYjJpCjRoWHBzMDBEVmliK0V4VkVSWWM1MFJtMGkzdXNGTHZsblY0L29EQUhYTkNOQitUOGRLMmRqU0VRYVNtWmtscDNMQXdHWm4KL0tEQkV0eEkrRVVxUGtQNkJuWDZuUHpTbFJYcFk3OWpZeTBQU0R1dEY3SE9wYXdReHowTHJoUkVObWdmZG81YnpNTndQWApXU3pGM0hSY0MxQ3JkWXhLV04rS2kwemVtcUVjbnRTQTVWMWpucnJpdVdUajdpbTZSR1FuSmcrRXVIeDlqL09wVE0zM3o0CndOcjFRTTFZOGdqajE4QUxWRFJwMC9HRDFBRGdwMDZ5UjNPSytYeFBLZ1B6SVpGN25ab29wbHVUUzVKTjdIQ2tEeFNsUm4KSllsbENoT1k4cGY1Z2UxNEFEUW5uTGErdTJRa3FzaUFNalIvN1hGRUthVE4wV3Q5MEU5NmZrRWthdDM3TkRkelQvTXh1agpxTmY2bzkrUS9YamVpUVpaemJQN253bTM0K3pqVlFBQUFBTUJBQUVBQUFHQVJCNkR3MkRicTdSR3NXeEtWUHRNOHpLbnRDClhyUmc2Z3RRRkZFclMyYWhRYU9ZTmFYWVpTcW40RmJucktYb0JWcndZNnBidnVuY2lnVE4zaHZtWDF4WDlzSE5ESFkrTU8KMmtuMUlOOTF0dVo0MUZjc2RKY3Ztc2FHZitsYnVNcDJMbVM2cXF4OXAyTmM1TnlXZ1U1S1lJYTBXM3hpSlFMTWVzYTdTQQpycVZBbDJ5ekx5Mkd4bzM0SlQyblNLRVBpWGE5YzBDR2wvSnJYV1FqTXQ3VzR5YjFobitjUWJUdkZUN0xXVXdxbGQ2bHRKCk1ETmczNVdabWJMeFh5UmM1TGlGN1hSR3VmUE5xa3h6Q1NoL1YyMjdtSGhwTlhPS3pqTWY2ZDdLOVhxdnMxU05aTXBmbjAKZnJtYW5qQkVXaVZnMXNrcHVXbEpVYjZON3I3VmFacG1vbGk1SXY3aTA5YytqeVd0Zk52K3B3VndSRS9hd1VSZEFMczNKKwpDTlc0aVNQQlFqMVVJc0EzUXFjd1lqVGk1ZWM4WlNtcU5BYzNqbTZMQ2p1bGtRYXBBWE1pTlVHZUpPbTF0UkFtVExPa0ZwCjBQZyt3Q3I1WEo1dDE0RklkOTBESkNvdVZnQk15UkRSSG9KU0RmaTdDWlJmL2pELzZCUERlZWlTczNKY2QyWWZKbEFBQUEKd0ZMdEhGNFhsZE9KRy9Tb0lnZ09WeDNDcUx4MGphRWt6SDRVOXJpK3F2cHgxYkZPNGFrOFBycjB5YjZDL0orUXVTU0o4LwpFa280cjM5SFJ1a3dqVzltR3FDeUZFWjFJMk5QNmpaK3ZYZzhJUnFuUG1jN050bHZqL2R4WTdmSTlUTGJlU3pvNGQ1NkRoCm0vOGVIWkZVUllweTVWQmVqTUtHUUtuQlBsM0gvVWtQZGE4Qjh6TzduYktnb1pIWUdqTE4xNUdTSG01MmxYalQ4aktVT1kKeWs1c2J4K2QrZUdtV29UcmlVWURMalFWa2toK1hHT3J4TnByMDcwbG81U0loMFJ3QUFBTUVBM1JPdXBDaHNiSmlldXlsaQp2R2ljUzBtdGxLRjFIR3Nia0FiSXFsTGcvbXR0dkVsanFMaWl2L2lhTGh6NXcwdCs1ZDFncy9RUDZIdkxzM0hPczMwTncxClY2V05oY091eFF3WUUxUUdYRGR0M25aUjVxUmdUUVB5YkFxOUhsbkxOKzdUUzVWUnhDeWRxbllqZG9KZUFiUUQyVy9ENmMKUUkzcjhoRTRuY3NDTWJJN2tiMHNMV3Q5ZVdxR2Z1QnlWd1VaYXdjRUhXMWVzS1MzcURZN2tCOGFEb1ZDdUNQbFRWbnJLZgo4d2pnMXNCUktNaTJUVW13U2Fyd0lQVmJsa3FSRjNBQUFBd1FEVTBVY3JscGQ5Sk5SZkpLYURzMFJMVVBIT2krb21uSWZ0Cngwd2J5aXlZUE4rS3Fsa2hGYVFEMHhpUDlTSm53ald3WVhpVEZRK2M0cy9KS2J2M0JpY2lubEVkK0hseFVVZGZ0Uld4Q2wKMzYrS2RSc1o3SXBwcFBOVmhQajZxYzBmTXN3NHZUSmdpY25nUndoNSttZEdQb1BXcVR3UlVQL2c4RW9JSjZ6ZVZpMXUzUQpVdmpReEFYd3BlUFFWRjE3U2lqS3J1UUxWRVJTZElVcU13eitHMERSOFNCN3VSOS9vMGx6V3RhUVRjUG9zQ2NDV05JdkdzCmp0UG5DdE8zWitCSk1BQUFBZGRIVXlNekl6UUdZek5pNTJjRzV6WlhKMmFXTmxMbU52YlhCaGJua0JBZ01FQlFZPQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K"


void test_ssh(SSH ssh, char *secret, char *exec_ssh_cmd){
  printf("ssh connect start\n");
  int res  = VCALL(ssh, config, "127.0.0.1", 22, "tu2323", secret);
  int ping = VCALL(ssh, ping);

  printf("ping result = %d\n", ping);
  int e = VCALL(ssh, exec_cmd, exec_ssh_cmd);

  printf("exec result = %d\n", e);
}


void main_ssh(){
  SSH  ssh_password   = DYN_LIT(SshAuthPassword, SSH, { });
  SSH  ssh_privatekey = DYN_LIT(SshAuthPrivateKey, SSH, {});
  char *exec_ssh_cmd  = "hostname";

  test_ssh(ssh_privatekey, B64_ENCODED_PRIVATE_KEY, exec_ssh_cmd);
  test_ssh(ssh_password, PASSWORD, exec_ssh_cmd);
}


int main(__attribute__((unused)) int argc, __attribute__((unused)) char **argv) {
  main_ssh();
  log_info("TEST2 OK");
}

